### PR TITLE
Adding method to format the autocomplete results.

### PR DESCRIPTION
**Pull request by raksbisht**
Adding method to format the autocomplete results.

### CODE REVIEW

**Comment by sickdyd** [comment]
@raksbisht Thank you for your PR!
Can you add tests for this?

**Comment by raksbisht** [comment]
ok sure @sickdyd

**Comment by raksbisht** [comment]
Thanks, @sickdyd  for merging the PR. Can you please update the npm package as well so we can start using it using npm?

**Comment by sickdyd** [comment]
@raksbisht Sorry for the wait, I updated the npm package!

**Comment by raksbisht** [comment]
Thanks you @sickdyd 😊

**Pull request merged**
